spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${env.DB_URL}
    username: ${env.DB_USERNAME}
    password: ${env.DB_PASSWORD}
  redis:
    host: ${env.REDIS_HOST}
    port: ${env.REDIS_PORT}

  jpa:
    properties:
      hibernate:
        format_sql: true
    show-sql: true

logging:
  level:
    config: classpath:logback.xml

decorator:
  datasource:
    p6spy:
      enable-logging: false