server:
  port: 8000
spring:
  cloud:
    gateway:
      default-filters:
        - name: GlobalFilter
          args:
            baseMessage: Spring Cloud Gateway GlobalFilter
            preLogger: true
            postLogger: true
#      routes:
#        - id: get-checklist
#          uri: http://localhost:8080/
#          predicates:
#            - Path=/api/check-list
#          filters:
#            - name: UserFilter
#              args:
#                baseMessage: Spring Cloud Gateway UserFilter
#                preLogger: true
#                postLogger: true
  profiles:
    include: oauth, s3
    active: prod
#  main:
#    web-application-type: reactive
#    allow-bean-definition-overriding: true