

-- MySQL Script generated by MySQL Workbench
-- Mon Mar 21 13:53:05 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema amattang
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema amattang
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `amattang` DEFAULT CHARACTER SET utf8 ;
USE `amattang` ;

DROP TABLE IF EXISTS basic_question;
DROP TABLE IF EXISTS answer_type_string;
DROP TABLE IF EXISTS answer_type_bool;
DROP TABLE IF EXISTS common_question_template;
DROP TABLE IF EXISTS common_question_template;
DROP TABLE IF EXISTS common_question_type_d_template;
DROP TABLE IF EXISTS common_question__template;
DROP TABLE IF EXISTS answer_type_d_answer;
DROP TABLE IF EXISTS answer_type_d;
DROP TABLE IF EXISTS answer_type_c;
DROP TABLE IF EXISTS answer_type_b;
DROP TABLE IF EXISTS answer_type_a;
DROP TABLE IF EXISTS answer;
DROP TABLE IF EXISTS question_to_answer;
DROP TABLE IF EXISTS check_list_common_question;
DROP TABLE IF EXISTS check_list_image;
DROP TABLE IF EXISTS custom_question;
DROP TABLE IF EXISTS check_list;
DROP TABLE IF EXISTS custom_category;
DROP TABLE IF EXISTS common_question_template;
DROP TABLE IF EXISTS common_question_type_d_template;
DROP TABLE IF EXISTS common_question;
DROP TABLE IF EXISTS user;


-- -----------------------------------------------------
-- Table `amattang`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `amattang`.`user` (
    `user_id` VARCHAR(500) NOT NULL,
    `provider` VARCHAR(20) NOT NULL,
    `name` VARCHAR(45) NOT NULL,
    PRIMARY KEY (`user_id`))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `amattang`.`common_question`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `amattang`.`common_question` (
                                                            `question_id` BIGINT NOT NULL,
                                                            `question` VARCHAR(255) NOT NULL,
    `main_category` VARCHAR(255) NOT NULL,
    `sub_category` VARCHAR(255) NULL,
    `rule` VARCHAR(1000) NULL,
    `description` VARCHAR(1000) NULL,
    `emoji` VARCHAR(60) NOT NULL,
    `ans_type` VARCHAR(10) NOT NULL,
    `d_type` VARCHAR(45) NOT NULL,
    `red_type` VARCHAR(10) NULL,
    `duplication` TINYINT NULL,
    `direction1` VARCHAR(45) NULL,
    `direction2` VARCHAR(45) NULL,
    `basic_type` VARCHAR(45) NULL,
    `setting` VARCHAR(50) NULL,
    PRIMARY KEY (`question_id`))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `amattang`.`check_list`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `amattang`.`check_list` (
                                                       `check_list_id` BIGINT NOT NULL AUTO_INCREMENT,
                                                       `user_user_id` VARCHAR(500) NOT NULL,
    `pinned` TINYINT NOT NULL,
    `image` VARCHAR(1000) NULL,
    `title` VARCHAR(100) NULL,
    `address` VARCHAR(300) NULL,
    `latitude` DECIMAL(11,8) NULL,
    `longitude` DECIMAL(11,8) NULL,
    `distance` VARCHAR(100) NULL,
    `room_type` VARCHAR(20) NULL,
    `area` VARCHAR(20) NULL,
    `floor` VARCHAR(20) NULL,
    PRIMARY KEY (`check_list_id`),
    INDEX `fk_check_list_user1_idx` (`user_user_id` ASC) VISIBLE,
    CONSTRAINT `fk_check_list_user1`
    FOREIGN KEY (`user_user_id`)
    REFERENCES `amattang`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `amattang`.`custom_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `amattang`.`custom_category` (
                                                            `custom_category_id` BIGINT NOT NULL AUTO_INCREMENT,
                                                            `name` VARCHAR(100) NOT NULL,
    `check_list_check_list_id` BIGINT NOT NULL,
    PRIMARY KEY (`custom_category_id`),
    INDEX `fk_custom_category_check_list1_idx` (`check_list_check_list_id` ASC) VISIBLE,
    CONSTRAINT `fk_custom_category_check_list1`
    FOREIGN KEY (`check_list_check_list_id`)
    REFERENCES `amattang`.`check_list` (`check_list_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `amattang`.`custom_question`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `amattang`.`custom_question` (
                                                            `custom_question_id` BIGINT NOT NULL AUTO_INCREMENT,
                                                            `custom_category_custom_category_id` BIGINT NOT NULL,
                                                            `question` VARCHAR(255) NULL,
    `checked` TINYINT NULL,
    PRIMARY KEY (`custom_question_id`),
    INDEX `fk_custom_question_custom_category1_idx` (`custom_category_custom_category_id` ASC) VISIBLE,
    CONSTRAINT `fk_custom_question_custom_category1`
    FOREIGN KEY (`custom_category_custom_category_id`)
    REFERENCES `amattang`.`custom_category` (`custom_category_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `amattang`.`check_list_image`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `amattang`.`check_list_image` (
                                                             `check_list_image_id` BIGINT NOT NULL AUTO_INCREMENT,
                                                             `check_list_check_list_id` BIGINT NOT NULL,
                                                             `url` VARCHAR(1000) NOT NULL,
    `main` TINYINT NOT NULL,
    PRIMARY KEY (`check_list_image_id`),
    INDEX `fk_check_list_image_check_list1_idx` (`check_list_check_list_id` ASC) VISIBLE,
    CONSTRAINT `fk_check_list_image_check_list1`
    FOREIGN KEY (`check_list_check_list_id`)
    REFERENCES `amattang`.`check_list` (`check_list_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `amattang`.`check_list_common_question`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `amattang`.`check_list_common_question` (
                                                                       `check_list_common_question_id` BIGINT NOT NULL AUTO_INCREMENT,
                                                                       `check_list_check_list_id` BIGINT NOT NULL,
                                                                       `common_question_question_id` BIGINT NOT NULL,
                                                                       `visibility` TINYINT NOT NULL,
                                                                       PRIMARY KEY (`check_list_common_question_id`),
    INDEX `fk_check_list_basic_question_check_list1_idx` (`check_list_check_list_id` ASC) VISIBLE,
    INDEX `fk_check_list_basic_question_basic_question1_idx` (`common_question_question_id` ASC) VISIBLE,
    CONSTRAINT `fk_check_list_basic_question_check_list1`
    FOREIGN KEY (`check_list_check_list_id`)
    REFERENCES `amattang`.`check_list` (`check_list_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    CONSTRAINT `fk_check_list_basic_question_basic_question1`
    FOREIGN KEY (`common_question_question_id`)
    REFERENCES `amattang`.`common_question` (`question_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `amattang`.`common_question_template`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `amattang`.`common_question_template` (
                                                                     `common_question_template_id` INT NOT NULL AUTO_INCREMENT,
                                                                     `common_question_question_id` BIGINT NOT NULL,
                                                                     `template` VARCHAR(45) NOT NULL,
    `red_type` TINYINT NOT NULL DEFAULT 0,
    PRIMARY KEY (`common_question_template_id`),
    INDEX `fk_common_question_type_d_template_common_question1_idx` (`common_question_question_id` ASC) VISIBLE,
    CONSTRAINT `fk_common_question_type_d_template_common_question1`
    FOREIGN KEY (`common_question_question_id`)
    REFERENCES `amattang`.`common_question` (`question_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `amattang`.`question_to_answer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `amattang`.`question_to_answer` (
                                                               `question_to_answer_id` BIGINT NOT NULL AUTO_INCREMENT,
                                                               `check_list_common_question_check_list_common_question_id` BIGINT NOT NULL,
                                                               PRIMARY KEY (`question_to_answer_id`),
    INDEX `fk_answer_check_list_common_question1_idx` (`check_list_common_question_check_list_common_question_id` ASC) VISIBLE,
    CONSTRAINT `fk_answer_check_list_common_question1`
    FOREIGN KEY (`check_list_common_question_check_list_common_question_id`)
    REFERENCES `amattang`.`check_list_common_question` (`check_list_common_question_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `amattang`.`answer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `amattang`.`answer` (
                                                   `answer_id` BIGINT NOT NULL AUTO_INCREMENT,
                                                   `type` VARCHAR(45) NOT NULL,
    `red_type` TINYINT NOT NULL DEFAULT 0,
    `question_to_answer_question_to_answer_id` BIGINT NOT NULL,
    PRIMARY KEY (`answer_id`),
    INDEX `fk_answer_question_to_answer1_idx` (`question_to_answer_question_to_answer_id` ASC) VISIBLE,
    CONSTRAINT `fk_answer_question_to_answer1`
    FOREIGN KEY (`question_to_answer_question_to_answer_id`)
    REFERENCES `amattang`.`question_to_answer` (`question_to_answer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `amattang`.`answer_type_bool`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `amattang`.`answer_type_bool` (
                                                             `answer_id` BIGINT NOT NULL,
                                                             `ans` TINYINT NOT NULL,
                                                             PRIMARY KEY (`answer_id`),
    CONSTRAINT `fk_answer_type_bool_answer1`
    FOREIGN KEY (`answer_id`)
    REFERENCES `amattang`.`answer` (`answer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `amattang`.`answer_type_string`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `amattang`.`answer_type_string` (
                                                               `answer_id` BIGINT NOT NULL,
                                                               `ans` VARCHAR(300) NOT NULL,
    PRIMARY KEY (`answer_id`),
    CONSTRAINT `fk_answer_type_string_answer1`
    FOREIGN KEY (`answer_id`)
    REFERENCES `amattang`.`answer` (`answer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;


SET foreign_key_checks = 1;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
